refactor: disjoint  build and test job

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -9,22 +9,34 @@ on:
 
 env:
   MIN_COVERAGE: 80
+  GO_VERSION: "1.20"
 
 jobs:
-  building-tests:
+  setup:
     runs-on: ubuntu-latest
     steps:
     - name: Setup Go Environment
-      # uses: actions/setup-go@v3
       uses: actions/setup-go@v3
       with:
-        go-version: "1.20"
+        go-version: ${{ env.GO_VERSION }}
 
     - name: Checkout code
       uses: actions/checkout@v3
 
     - name: Install dependencies
       run: go mod tidy
+
+  unit-tests:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+    - name: Setup Go Environment
+      uses: actions/setup-go@v3
+      with:
+        go-version: ${{ env.GO_VERSION }}
+
+    - name: Checkout code
+      uses: actions/checkout@v3
 
     - name: Run unit tests
       run: go test -v ./...
@@ -34,12 +46,28 @@ jobs:
         go test -coverprofile=coverage.out ./...
         go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}' > coverage_percent.txt
         COVERAGE=$(cat coverage_percent.txt)
+        if ! command -v bc &> /dev/null; then
+          echo "bc command not found, installing..."
+          sudo apt-get update && sudo apt-get install -y bc
+        fi
         if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
-          echo "Code coverage is below $MIN_COVERAGE%: $COVERAGE%"
+          echo -e "\033[0;31mCode coverage is below $MIN_COVERAGE%: $COVERAGE%\033[0m"
           exit 1
         else
-          echo "Code coverage is sufficient: $COVERAGE%"
+          echo -e "\033[0;32mCode coverage is sufficient: $COVERAGE%\033[0m"
         fi
+
+  build:
+    runs-on: ubuntu-latest
+    needs: unit-tests
+    steps:
+    - name: Setup Go Environment
+      uses: actions/setup-go@v3
+      with:
+        go-version: ${{ env.GO_VERSION }}
+
+    - name: Checkout code
+      uses: actions/checkout@v3
 
     - name: Build Go binary
       run: go build -o myapp .
